### ISSUE TITLE
Please update firestore API to include missing endpoints

### ISSUE THREAD

**Issue by gmlewis** [googleapis/elixir-google-api#108]
Using the Google APIs Explorer, I see that firestore has the following endpoint:
https://developers.google.com/apis-explorer/#search/firestore/m/firestore/v1beta1/firestore.projects.databases.documents.get

However, the Elixir client library does not appear to have that yet:

https://github.com/GoogleCloudPlatform/elixir-google-api/blob/master/clients/firestore/lib/google_api/firestore/v1beta1/api/projects.ex

@chingor13 - is this the correct way to request updates?

Thank you!

**Comment by chingor13** [comment]
Thanks for reporting this. 

It looks like there's a bigger issue with our conversion from Google Discovery format to OpenApi v3. The Google Discovery path is `"path": "v1beta1/{+name}"` which is not unique and cannot be expressed in OpenApi v3. We'll have to figure out how to use the `"flatPath": "v1beta1/projects/{projectsId}/databases/{databasesId}/documents/{documentsId}/{documentsId1}"` attribute. Unfortunately, the inner fields are not described in the Discovery parameters so we'll have to figure that out. Also, unfortunately, it will likely change the API function signatures to take individual parameters (although it's arguably a better experience than forcing the developer to build the `name` parameter).

**Comment by JustinBeckwith** [comment]
Greetings!  This should now be available in the latest version:
https://github.com/googleapis/elixir-google-api/blob/master/clients/firestore/lib/google_api/firestore/v1beta1/api/projects.ex#L586

**Comment by gmlewis** [comment]
Thank you, Justin!
It's great to hear from you. I hope all is well! :smiley:
