### ISSUE TITLE
Automatically update README installation instructions for new versions

### ISSUE THREAD

**Issue by dwarner** [googleapis/elixir-google-api#1108]
The README needs updated to latest version `{:google_api_o_auth2, "~> 0.2.0"}`:
https://github.com/googleapis/elixir-google-api/tree/master/clients/o_auth2

Not sure if this will help in future:
https://dockyard.com/blog/2019/02/22/keep-your-readme-install-instructions-up-to-date

**Comment by dazuma** [comment]
This is a very good point, and it applies to all the libraries.

**Comment by dazuma** [comment]
The code generation is now updating the README. Thanks for the report!
