### ISSUE TITLE
Can someone provide an example?

### ISSUE THREAD

**Issue by kwasham** [googleapis/elixir-google-api#111]
Sorry for the basic question, but I cant get Firestore to work. In my IEX session, I type the following:

iex(16)> GoogleApi.Firestore.V1beta1.Api.Projects.firestore_projects_databases_documents_list(           
...(16)> (GoogleApi.Firestore.V1beta1.Connection),                                            
...(16)> "projects/rndm-49de0/databases/(default)",                                           
...(16)> "thoughts",                                                                          
...(16)> [oauth_token: "my_oauth_key.apps.googleusercontent.com"])

I Get the following errors:

** (FunctionClauseError) no function clause matching in GoogleApi.Gax.Request.add_optional_params/3    
    
    The following arguments were given to GoogleApi.Gax.Request.add_optional_params/3:
    
        # 1
        %GoogleApi.Gax.Request{
          body: [],
          file: [],
          header: [],
          method: :get,
          query: [],
          url: "/v1beta1/projects/rndm-49de0/databases/(default)/thoughts"
        }
    
        # 2
        %{
          "$.xgafv": :query,
          access_token: :query,
          alt: :query,
          callback: :query,
          fields: :query,
          key: :query,
          "mask.fieldPaths": :query,
          oauth_token: :query,
          orderBy: :query,
          pageSize: :query,
          pageToken: :query,
          prettyPrint: :query,
          quotaUser: :query,
          readTime: :query,
          showMissing: :query,
          transaction: :query,
          uploadType: :query,
          upload_protocol: :query
        }
    
        # 3
        [:oauth_token,
         "my_oauth_token.apps.googleusercontent.com"]
    
    Attempted function clauses (showing 2 out of 2):
    
        def add_optional_params(request, _, [])
        def add_optional_params(request, definitions, [{key, value} | tail])
    
    (google_gax) lib/google_api/gax/request.ex:116: GoogleApi.Gax.Request.add_optional_params/3
    (google_api_firestore) lib/google_api/firestore/v1beta1/api/projects.ex:350: GoogleApi.Firestore.V1beta1.Api.Projects.firestore_projects_databases_documents_list/4

not sure if this is the right place to ask this question, but Im at a standstill until I figure this out. Any help would be appreciated. Thanks in advance.

**Comment by lpil** [comment]
Hi @kwasham it looks like your last argument is `[:oauth_token, "my_oauth_token.apps.googleusercontent.com"]` when it should be `[oauth_token: "my_oauth_token.apps.googleusercontent.com"]`

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
