### ISSUE TITLE
errors come in as unparsed json, while successes are parsed.

### ISSUE THREAD

**Issue by vans163** [googleapis/elixir-google-api#1119]
If we get an error from the API, we get an unparsed body, while the successes the library parses the json. For failures I think the result should be parsed if its json.

This would allow you to at least pattern match on the error without having to do a layer of indirection in the case of errors.

**Comment by zeroasterisk** [comment]
Do you think it is related to Poison version 4? See #1232 for a summary.
Can you downgrade Poison and see if that fixes it?

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
