### ISSUE TITLE
Firestore batchGet decoding breaks

### ISSUE THREAD

**Issue by aaruel** [googleapis/elixir-google-api#112]
When retrieving documents from the batchGet endpoint it returns a body as such:

```elixir
"[{\n  \"found\": {\n    \"name\": \"projects/xxxxx/databases/(default)/documents/xxxxx\",\n    \"fields\": {...},\n    \"createTime\": \"2018-xxxxxxxZ\",\n    \"updateTime\": \"2018-xxxxxxxZ\"\n  },\n  \"readTime\": \"2018-xxxxxxxZ\"\n}\n]"
```

When reaching the decoder [here](https://github.com/GoogleCloudPlatform/elixir-google-api/blob/master/clients/firestore/lib/google_api/firestore/v1beta1/api/projects.ex#L148) it breaks because of the brackets the body is wrapped in when getting [here](https://github.com/devinus/poison/blob/master/lib/poison/decoder.ex#L73) because of [this](https://github.com/GoogleCloudPlatform/elixir-google-api/blob/master/clients/firestore/lib/google_api/firestore/v1beta1/model/batch_get_documents_response.ex#L19).

**Comment by JustinBeckwith** [comment]
@aaruel we've gone through a pretty significant rewrite since this came up.  Could we trouble you to verify this is still an issue with the latest version?

**Comment by SurferJeffAtGoogle** [comment]
@aaruel We've heard no response in over two months, so I assume the latest version fixed the issue for you.  If this issue is still causing problems for you, please re-open.
