### ISSUE TITLE
How to upload data from memory to Cloud Storage?

### ISSUE THREAD

**Issue by stefanluptak** [googleapis/elixir-google-api#1197]
Is it possible to upload data to Cloud Storage directly from memory without providing local file path?

I would like to do something like this:

```elixir
conn = GoogleApi.Storage.V1.Connection.new("SOME_TOKEN")

{:ok, object} =
  GoogleApi.Storage.V1.Api.Objects.storage_objects_insert_simple(
    conn,
    "SOME_BUCKET",
    "multipart",
    %{name: "file.txt"},
    "Hello, World! This is the content of the file."
)
```

I searched the documentation, even tried to look into the source code, but with no luck.

Thanks a lot. :-)

**Comment by EskiMag** [comment]
OK, I figured it out. I just needed to use this:

```elixir
conn = GoogleApi.Storage.V1.Connection.new("TOKEN")

{:ok, object} =
  GoogleApi.Storage.V1.Api.Objects.storage_objects_insert(
    conn,
    "BUCKET_NAME",
    body: "Hello, World! This is the content of the file.",
    name: "file.txt"
  )
```

I was confused by error message happening because of the #972 - any idea when the fix will be released?

**Comment by dazuma** [comment]
We have a bunch of updates queued up and expect to do a general release in the next week or two. It may have to come after the GCP Next conference is over because most of us are working there.

**Comment by EskiMag** [comment]
Thanks for the info @dazuma 
I am using a modified `google_api_storage` as a local dependency until then without a problem.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
