### ISSUE TITLE
Storage: URI encoding fails for spaces

### ISSUE THREAD

**Issue by hauptbenutzer** [googleapis/elixir-google-api#120]
Hi! 

Elixir's `URI.encode_www_form` is used throughout this client library. Unfortunately this fails for Storage Object names containing spaces. Apparently, this is because `encode_www_form` has [special handling for spaces](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/uri.ex#L303) and replaces it with a `+` instead of the [expected percent-encoded](https://cloud.google.com/storage/docs/json_api/#encoding) `%20`. 

This seems to be the wanted encoding method:
```elixir
iex> URI.encode("some/path/File with späces.zip", &URI.char_unreserved?/1)
"some%2Fpath%2FFile%20with%20sp%C3%A4ces.zip"
```

I am not sure if a change to the generator template would affect the other APIs, but that would appear to be the easiest way to fix this.

**Comment by lpil** [comment]
This has bit me today, thank you for the fix @hauptbenutzer 

I hope the problem is patched soon :)
