### ISSUE TITLE
Need to add synth.metadata to all directories

### ISSUE THREAD

**Issue by dazuma** [googleapis/elixir-google-api#1211]
Synthtool is spitting out errors saying the file is missing. I'm not sure if this is having downstream effects like incomplete autogen.

- [x] Fix metadata path in autosynth
- [ ] Update .gitignore to fix allow `synth.metadata`

**Comment by chingor13** [comment]
We now have an open PR on autosynth to fix the output directory. Then we will want to remove the .gitignore entry to allow the synth.metadata file to be added to git.

**Comment by chingor13** [comment]
Confirmed that autosynth is correctly 

From #1436
> synthtool > Wrote metadata to clients/service_control/synth.metadata.
