### ISSUE TITLE
Firestore run_query not working properly

### ISSUE THREAD

**Issue by dominikdnd** [googleapis/elixir-google-api#1231]
I always run into an issue, when calling: GoogleApi.Firestore.V1beta1.Api.Projects.firestore_projects_databases_documents_run_query, as shown below. Please can anybody help? Thanks in advance!

`query = %GoogleApi.Firestore.V1beta1.Model.RunQueryRequest{ structuredQuery: %{ :from => %{ :collectionId => "demo" }, :limit => 1 }}
        GoogleApi.Firestore.V1beta1.Api.Projects.firestore_projects_databases_documents_run_query(conn, "projects/demo/databases/(default)/documents", [body: query])`

Result:
`** (BadMapError) expected a map, got: [%{"readTime" => "2019-04-07T20:23:48.219664Z"}]
    (elixir) lib/map.ex:437: Map.get([%{"readTime" => "2019-04-07T20:23:48.219664Z"}], "document", nil)
    lib/poison/decoder.ex:53: anonymous fn/3 in Poison.Decode.transform_struct/4
    (stdlib) maps.erl:257: :maps.fold_1/3
    lib/poison/decoder.ex:52: Poison.Decode.transform_struct/4
    lib/poison.ex:70: Poison.decode/2`

**Comment by zeroasterisk** [comment]
related to #1232 - we will be working on this soon.

**Comment by brunoripa** [comment]
I have the very same problem and the suggested fix does not work. `google_gax` already pins `poison` at < 4.0 but i still have the error:

```
** (BadMapError) expected a map, got: [%{"document" => %{"createTime" => "2019-07-29T15:56:15.862840Z", "fields" => %{"name" => %{"stringValue" => "Bruno Ripa"}}, "name" => "projects/cloud-run-example-01/databases/(default)/documents/users/1", "updateTime" => "2019-07-29T16:37:05.776930Z"}, "readTime" => "2019-08-25T09:25:46.284870Z"}]
    (elixir) lib/map.ex:451: Map.get([%{"document" => %{"createTime" => "2019-07-29T15:56:15.862840Z", "fields" => %{"name" => %{"stringValue" => "Bruno Ripa"}}, "name" => "projects/cloud-run-example-01/databases/(default)/documents/users/1", "updateTime" => "2019-07-29T16:37:05.776930Z"}, "readTime" => "2019-08-25T09:25:46.284870Z"}], "document", nil)
    (poison) lib/poison/decoder.ex:53: anonymous fn/3 in Poison.Decode.transform_struct/4
    (stdlib) maps.erl:232: :maps.fold_1/3
    (poison) lib/poison/decoder.ex:52: Poison.Decode.transform_struct/4
    (poison) lib/poison.ex:70: Poison.decode/2
```

after running the following snippet:

```
alias Goth.Token
{:ok, token} = Token.for_scope("https://www.googleapis.com/auth/datastore")
conn = GoogleApi.Firestore.V1.Connection.new(token.token)
q = %GoogleApi.Firestore.V1beta1.Model.RunQueryRequest{
  structuredQuery: %{
    :from => %{:collectionId => "users"},
    :limit => 1
  }
}
pname = "projects/cloud-run-example-01/databases/(default)/documents"
GoogleApi.Firestore.V1.Api.Projects.firestore_projects_databases_documents_run_query(conn, pname, [body: q])
```

**Comment by dazuma** [comment]
I believe I've found the issue here. Will release a fixed version of the `google_gax` package shortly.
