### ISSUE TITLE
poison version 4 breaks decoding

### ISSUE THREAD

**Issue by zeroasterisk** [googleapis/elixir-google-api#1232]
Poison Version 4 changes interface for decoding into structs.
This results in an error like:
> function Poison.Decode.decode/2 is undefined or private

Poison.Decode.decode -> Poison.Decode.transform (different options)

https://github.com/devinus/poison/compare/3.1.0...master#diff-008cd84cae620b00278a75ce952aa006

Will need to update `GoogleApi.Gax.ModelBase` to handle either version.

Until fixed, you can bypass this by forcing old `:poison` in your `mix.exs`
```elixir
    {:poison, "~> 3.1.0"}, # force old poison
```

**Comment by absolutejam** [comment]
It's been a while, but I've just revisited this code and updating the lib from `0.0.1` to `0.9.1` has fixed this issue. Means I can remove a lot of boilerplate from my code and just use these API calls :+1:

**Comment by SurferJeffAtGoogle** [comment]
@zeroasterisk Does @absolutejam's comment fix the issue for you too?

**Comment by dazuma** [comment]
@JustinBeckwith This is still an issue. (That the libraries are incompatible with the latest poison.) We've only papered over it by pinning to an earlier version.

**Comment by zeroasterisk** [comment]
Yes, sorry I have not had any time to look into Elixir code in months (woe is me). But until we abstract out the marshaling of structs, I think this issue remains... and the longer it remains, the more new users will be blocked/stumbled by it.
