### ISSUE TITLE
Publish android_publisher API?

### ISSUE THREAD

**Issue by elfenlaid** [googleapis/elixir-google-api#1242]
Hi there, 
I've encountered an issues with `google_api_android_publisher` package. 

It has been [generated](https://github.com/googleapis/elixir-google-api/tree/master/clients/android_publisher) and works, but for some reason hasn't been uploaded to hex.

May I know a reason behind it, has it been done intentionally or there are some package issues?

Thanks.

**Comment by zeroasterisk** [comment]
related to #1232 - we will be working on this soon.

**Comment by elfenlaid** [comment]
ah, thanks

**Comment by linjunpop** [comment]
As a workaround, declare following in `mix.exs`:

```
      {:google_api_android_publisher, "~> 0.1.0",
       github: "googleapis/elixir-google-api", sparse: "clients/android_publisher"},
```
