### ISSUE TITLE
Chat generator is reordering methods

### ISSUE THREAD

**Issue by dazuma** [googleapis/elixir-google-api#1256]
See https://github.com/googleapis/elixir-google-api/pull/1214
The generator seems to have merely reordered the methods. This seems to happen for certain libraries (a small number of them).

**Comment by chingor13** [comment]
This is actually the same issue where OpenApi is keyed by path. In this case, the {+name} path is overloaded by 2 separate endpoints and cannot be converted to OpenApi without losing parameter information.
