### ISSUE TITLE
Improve generated code documentation

### ISSUE THREAD

**Issue by AndrewDryga** [googleapis/elixir-google-api#24]
Hi there,

Even though it's not fully related to this repo, I think It's important to have nice and readable docs even for generated documentation. 

You can [see here](https://hexdocs.pm/google_api_cloud_error_reporting/GoogleApi.CloudErrorReporting.V1beta1.Api.Projects.html) that there are html tags and other artifacts that can be easily replaced with supported markdown syntax helpers.

This can be addressed by either improving code generator for https://github.com/swagger-api/swagger-codegen or by using custom code generator in this repo.

**Comment by dazuma** [comment]
We did eventually implement a custom generator for this repo, and greatly improved the formatting of the docs.
