### ISSUE TITLE
[Compute] New codegen renamed Model.HttpHealthCheck to HTTPHealthCheck

### ISSUE THREAD

**Issue by dazuma** [googleapis/elixir-google-api#2435]
New codegen renamed Model.HttpHealthCheck to HTTPHealthCheck but didn't rename the uses. As a result, the new codegen doesn't build.

**Comment by chingor13** [comment]
note that in the compute API there are 2 different types: HttpHealthCheck and HTTPHealthCheck :(

**Comment by dazuma** [comment]
@chingor13 Really?? How is it that the new codegen renamed it then: https://github.com/googleapis/elixir-google-api/commit/a0f3d883828ff869a76c9f50ef567c5048731347#diff-381c25ef9ef51657ed249f2f0398de20

**Comment by dazuma** [comment]
I know there's HttpHealthCheck, Http2HealthCheck, and HttpsHealthCheck...
