### ISSUE TITLE
Drive and Gmail clients not published to hex

### ISSUE THREAD

**Issue by storm255** [googleapis/elixir-google-api#31]
Are all the client libraries automatically being published to hex.  I noticed that drive and gmail were not available.  I am having trouble building drive locally.

https://hex.pm/users/google-cloud

**Comment by chingor13** [comment]
The file upload portions of these APIs are not easily generated at the moment. See #1. We have a manual step that needs to happen before we can publish these and it's being worked on.

**Comment by storm255** [comment]
Understood.  Thanks for the effort.

I'm afraid I am not able to help as I am not building it successfully locally either.  I will wait patiently :) and keep trying.

Thanks again.

**Comment by chingor13** [comment]
We'll keep this open to keep it visible that it's requested and so you can get notified when it's fixed.

**Comment by f34nk** [comment]
+1

**Comment by chingor13** [comment]
@sahrizvi It's more of a question of testing that the file uploads work for each affected API, which we haven't had time to do. It's more time consuming as these APIs are also ones that require an OAuth 2.0 workflow - so service accounts and `goth` won't work for them (you must authorize on behalf of an authenticated user).

That said, I took a stab at the Drive API today and opened a PR in #67

**Comment by sahrizvi** [comment]
@chingor13 Thanks a lot for taking the time to respond (and that's one huge PR for Drive API)!
I understand, this requires a significant time commitment. At my workplace, I was considering migrating our email delivery infrastructure from Python to Elixir, hence enquired here. 
Thanks for the great work here, really appreciate it!

**Comment by storm255** [comment]
@sahrizvi @chingor13 Agreed, this is an ongoing and huge effort that is much appreciated.  

I look forward to helping in some small way during our implementation.

**Comment by chingor13** [comment]
Drive should now be available on hex: https://hex.pm/packages/google_api_drive

**Comment by storm255** [comment]
Thank you so much @chingor13.  I appreciate your effort so much.  I have been testing the other branch and will definitely give this a try now.

Have a great day.  You deserve it.

**Comment by f34nk** [comment]
Thank you @chingor13 
This is awesome! Greetings from Berlin

**Comment by sahrizvi** [comment]
Wow...thank you very much @chingor13 !! This will be a big help to me and a lot of other folks in the Elixir ecosystem.

**Comment by dazuma** [comment]
Both google_api_drive and google_api_gmail are on hex as of about 6 months ago. I'm going to close this.
