### ISSUE TITLE
Support Google Places API

### ISSUE THREAD

**Issue by krainboltgreene** [googleapis/elixir-google-api#3408]
Details: 
  - https://developers.google.com/places/web-service/intro
  - https://developers.google.com/places/web-service/client-library

Alternative implementations: 
  - https://github.com/sntran/google_maps
  - https://github.com/seanabrahams/google-api-elixir-client
  - https://github.com/techgaun/ex_google

**Comment by dazuma** [comment]
Unfortunately, this is probably out of scope for this particular project. We're focused on APIs that are covered by Google's discovery service (i.e. that have a machine-readable API definition and thus clients can be generated automatically.) The Places API isn't one of those. Its client has to be handwritten. For now, I suggest using one of the existing implementations that you've listed.
