### ISSUE TITLE
Translate model does not match specification

### ISSUE THREAD

**Issue by xpgdk** [googleapis/elixir-google-api#3409]
According to https://translation.googleapis.com/$discovery/rest?version=v2 `DetectionsResource` is an array of objects that have attributes `isReliable`, `confidence`, and `language`.
However, in the model files generated,  `GoogleApi.Translate.V2.Model.DetectionsResource` is a struct with the fields `isReliable`, `confidence`, and `language`.

Both in the spec and the generated model files, `DetectionsListResponse` is an object with an attribute `detections` that is an array of `DetectionResource`.

So, the API has two levels of arrays, while the model only has one.

**Comment by dazuma** [comment]
This has been diagnosed and a fix is in progress.

**Comment by dazuma** [comment]
The fix has been merged and will be present when the next release is cut tonight.
