### ISSUE TITLE
(UndefinedFunctionError) function Poison.encode_to_iodata!/1 is undefined or private

### ISSUE THREAD

**Issue by Adzz** [googleapis/elixir-google-api#3414]
Since upgrading our google elixir libraries (google_api_cloud_tasks, google_api_big_query) all tests fail as (I _think_ hard to tell from the commits?) Poison has been upgraded to version 4, meaning the function `Poison.encode_to_iodata!/1` no longer exists.

See the Poison issue here:  https://github.com/devinus/poison/issues/172

**Comment by dazuma** [comment]
Try pinning Poison to version 3 explicitly in your `mix.exs`. The libraries should be compatible with either version of Poison.

**Comment by dazuma** [comment]
Closing this, assuming the above comment resolved the issue. Feel free to reopen if it is still an issue.
