### ISSUE TITLE
Objects.storage_objects_get/4 with [alt: "media"] opts raises error because object can not be decoded into a struct

### ISSUE THREAD

**Issue by jbernardo95** [googleapis/elixir-google-api#3573]
If we call `Objects.storage_objects_get/4` with `[alt: "media"]` as `opts` an error is returned because the object contents [can not be decoded into a struct](https://github.com/googleapis/elixir-google-api/blob/master/clients/storage/lib/google_api/storage/v1/api/objects.ex#L329).

This is because when `alt=media` is used the object data is retrieved instead of the metadata. From [docs](https://cloud.google.com/storage/docs/json_api/v1/objects/get):

> Retrieves object metadata. When alt=media is included as a query parameter, retrieves object data.

**Comment by stefpankov** [comment]
You should pass the `decode: false` option in the fourth parameter.
Example:
```elixir
Objects.storage_objects_get(connection, bucket, path, [alt: "media"], [decode: false])
```
The fourth options parameter is actually sent to the `decode/2` function of the `GoogleApi.Gax.Response` module which provides the following options:

`opts` (*type:* `keyword()`) - [optional] Optional parameters
 - `:dataWrapped` (*type:* `boolean()`) - If true, the remove the wrapping "data" field. Defaults to false.
- `:decode` (*type:* `boolean()`) - If false, returns the entire reponse. Defaults to true.
- `:struct` (*type:* `module`)

**Comment by dazuma** [comment]
An update is in progress that will set `decode: false` by default on download calls when `alt: "media"` is set.

**Comment by dazuma** [comment]
The update is merged, and should be present when the next release is cut tonight.
