### ISSUE TITLE
How to authenticate with service account?

### ISSUE THREAD

**Issue by stefan-vatov** [googleapis/elixir-google-api#4006]
Hi,

I have what seems to be a really basic problem, I'm trying to use `GoogleApi.Firestore` to connect to Cloud Firestore using a service account.

Let me preface by saying that I'm still fairly new to both Elixir and GCP, so I'm guessing I've overlooked something.

Looking through the Firestore docs and in this repo, the example given is to use the environment variable

```bash
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service_account.json
```

Doing that doesn't seem to have any effect when I try and make requests. I tried making two different ones in iex:

```Elixir
GoogleApi.Firestore.V1.Api.Projects.firestore_projects_databases_documents_list_collection_ids(
  GoogleApi.Firestore.V1.Connection.new(),
  "projects/<project-name>/databases/(default)/documents")
```

```Elixir
GoogleApi.Firestore.V1.Api.Projects.firestore_projects_databases_documents_list(
  GoogleApi.Firestore.V1.Connection.new(),
  "projects/<project-name>/databases/(default)/documents",
  "test")
```

In both cases, the response comes back with

```Elixir
   body: "{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"Missing or insufficient permissions.\",\n    \"status\": \"PERMISSION_DENIED\"\n  }\n}\n",
```

I tried with and without setting `GOOGLE_APPLICATION_CREDENTIALS`. The response is all the same. Checking with `System.get_env` to confirm the variable is available/missing in each case.

For a while, I thought it might be the IAM roles and permissions, but currently, the account has `Cloud Datastore Owner` & `Owner` in that project. The second one for debugging purposes to make sure that it is not a lack of permissions.

Searching through this repository for references to the `GOOGLE_APPLICATION_CREDENTIALS` I didn't find any direction why it's not being picked up.

Docs [here](https://cloud.google.com/docs/authentication#getting_credentials_for_server-centric_flow) mention

> Cloud Client Libraries will automatically find and use the service account credentials by using the GOOGLE_APPLICATION_CREDENTIALS environment variable.

There is also [this PR](https://github.com/googleapis/elixir-google-api/pull/1233) open with some examples. It does use the variable before using tests, but the actual code has what I think is [OAuth2 token generation](https://github.com/googleapis/elixir-google-api/pull/1233/files#diff-2ef44c6a67646aa874c91a8c71014ba9R22).

What is the recommended way to connect using a service account?

**Comment by mpope9** [comment]
Your issue if phrased better than my issue here: https://github.com/googleapis/elixir-google-api/issues/3988. Closing in favor of this one.

**Comment by Adzz** [comment]
I'm not sure if this helps, but this is what we do. We use [Goth](https://github.com/peburrows/goth), in config we do this:

```elixir
config :goth, json: System.fetch_env!("GOOGLE_APPLICATION_CREDENTIALS")
```

Then in our code we do something like:
```elixir
{:ok, %{token: token}} = Goth.token_for_scope("https://www.googleapis.com/auth/datastore")
```
That token can then either be used to make a HTTP request like so:
```elixir
headers = [
      {"content-type", "application/json"},
      {"authorization", "Bearer #{token}"},
      {"accept", "application/json"}
    ]
HTTPoison.post("my_google_url", body, headers)
```

OR can be used in the way the specific google API requires. (I haven't used firestore butI imagine it's similar to below)

```elixir
GoogleApi.Firestore.V1.Connection.new(token)
|> GoogleApi.Firestore.V1.Api.Projects.firestore_projects_databases_documents_get("projects/#{project_id}/databases/#{database_id}/documents/#{document_path}")
```

**Comment by stefan-vatov** [comment]
Thank you for sharing your solution @Adzz .

I was wondering if something like this might be necessary. Reading the [Goth docs](https://hexdocs.pm/goth/Goth.Token.html#queue_for_refresh/1) it states:

> Goth automatically handles refreshing tokens for you, so you should rarely if ever actually need to call this method manually.

Have you had to write any additional logic around the token management?

**Comment by Adzz** [comment]
No problem. No I haven’t had to worry about refreshing tokens, so yea i’m assuming goth handles that under the hood.

**Comment by stefan-vatov** [comment]
The suggestion by @Adzz did work for me. 

A bit late on the reply, but I guess better late than never 😬
