### ISSUE TITLE
Hexdocs are stylized instead of showing asterisks

### ISSUE THREAD

**Issue by hexedpackets** [googleapis/elixir-google-api#4442]
For parameters that are documented with multiple asterisks as placeholders, hexdocs ends up formatting the string with italics instead of showing the asterisk. 

Example: For [GoogleApi.Container.V1.Api.Projects.container_projects_locations_clusters_get/4](https://hexdocs.pm/google_api_container/0.12.1/GoogleApi.Container.V1.Api.Projects.html#container_projects_locations_clusters_get/4) the `name` parameter shows  'projects/*/locations/*/clusters/*' instead of  'projects/\*/locations/\*/clusters/\*'.

**Comment by dazuma** [comment]
Thanks. Yes, there's a bunch of these that need to be cleaned up. I've opened a change request in the upstream source that these docs get generated from.

**Comment by dazuma** [comment]
We've cleaned up a bunch of these. Closing this issue for now. If you find additional examples, feel free to open a new issue and I'll pass them along.
