### ISSUE TITLE
Monitoring API: Incorrect URI encoding of metric_descriptors_id causes error

### ISSUE THREAD

**Issue by monkybrain** [googleapis/elixir-google-api#4600]
`GoogleApi.Monitoring.V3.Api.Projects.monitoring_projects_metric_descriptors_get` and other functions that need a `metric_descriptors_id` fail due to incorrect URI encoding.

The `URI.encode/2` predicate `URI.char_unreserved?/1` turns `/` into `%2f`, turning Metric Descriptor IDs like `custom.googleapis.com/test` into `custom.googleapis.com%2Ftest`.

Example:

https://github.com/googleapis/elixir-google-api/blob/61edef19a5e2c7c63848f7030c6d8d651e4593d4/clients/monitoring/lib/google_api/monitoring/v3/api/projects.ex#L1166-L1169

I suggest removing the predicate for these calls.

**Comment by dazuma** [comment]
Confirmed, certain path elements (that can appear at the end of the path) do allow `/`. I'll see what we can do to fix this in the generator.

**Comment by monkybrain** [comment]
@dazuma great, thanks!
