### ISSUE TITLE
SSL v3: google_api_big_query 0.38.0  breaks with esl-erlang OTP 23

### ISSUE THREAD

**Issue by BobBallance** [googleapis/elixir-google-api#5091]
After upgrading to esl-erlang OTP 23, the call to `GoogleApi.BigQuery.V2.Connection.new(token)` fails with an ssl error. The reason for the failed connection includes:
 
> {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}

SSL V3 was dropped in OTP 23. [SSL Release Notes](http://erlang.org/doc/apps/ssl/notes.html#ssl-10.0) and [SSL Compliance](http://erlang.org/doc/apps/ssl/standards_compliance.html)

Configuration:
   OS: Debian 10
   Erlang: esl-erlang 1:23.0-1 
   Elixir: Elixir 1.10.3 
   google_api_big_query 0.38.0

**Comment by dazuma** [comment]
@BobBallance Can you verify which versions of the `google_gax` and `tesla` packages you're using?

**Comment by BobBallance** [comment]
I’m at

google_gax:   0.3.2
tesla 1.3.3


. . . Bob
