### ISSUE TITLE
Structs with optional fields have wrong type specifications

### ISSUE THREAD

**Issue by michallepicki** [googleapis/elixir-google-api#6146]
When using the APIs together with the [elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls) VSCode extension, I noticed I'm getting a lot of dialyzer errors. This is because of wrong specs in **most** of the structs.

Whenever a struct can be returned from the libraries with `nil` fields, it should be noted as such in the used type specification. 

Example 1:

[gmail user history.list](https://github.com/googleapis/elixir-google-api/blob/master/clients/gmail/lib/google_api/gmail/v1/api/users.ex#L1306) returns a [ListHistoryResponse.t()](https://github.com/googleapis/elixir-google-api/blob/master/clients/gmail/lib/google_api/gmail/v1/model/list_history_response.ex#L32) which in its type definition specifies the `history` field to be of type `list(GoogleApi.Gmail.V1.Model.History.t())` but in reality, it can be `nil` (which is weird on its own because I would expect an empty list in this particular scenario, so maybe it's a bug? Not sure).

Example 2:

In the same resource, each [History.t()](https://github.com/googleapis/elixir-google-api/blob/master/clients/gmail/lib/google_api/gmail/v1/model/history.ex#L38) contains `messages` of type [`list(GoogleApi.Gmail.V1.Model.Message.t())`](https://github.com/googleapis/elixir-google-api/blob/master/clients/gmail/lib/google_api/gmail/v1/model/message.ex#L37) but structs found there do not align with this type. The type specifies many fields to be filled in: `:historyId => String.t(),`, `:payload => GoogleApi.Gmail.V1.Model.MessagePart.t(),`, `:raw => String.t(),` etc, but `history.list` returns `nil` for almost all of them.

Proposed solution:

Make sure that whenever a function is documented to return a struct type, this type is general enough to capture all possible returned structs, including `nil`s in optional fields. As a quick fix without introducing breaking changes to the library, those fields in type specs can be amended with ` | nil`. E.g.:

```
defmodule GoogleApi.Gmail.V1.Model.Message do
  @type t :: %__MODULE__{
          :historyId => String.t() | nil,
```

etc

**Comment by dazuma** [comment]
Thanks for the solution proposal! I applied it in #7406. Will regenerate and rerelease over the next couple days.
