### ISSUE TITLE
Problem copying objects with a `/` in the path with latest client

### ISSUE THREAD

**Issue by hassox** [googleapis/elixir-google-api#6352]
This was not a problem with the old client (0.22.1) we went up to the latest version and then back down.

When we try to copy an object with a name like: `assets/abcde.png` from one bucket to another, the _from_ side in the request becomes URL escaped so the `/` becomes `%2F` and seems to break it.

```
https://storage.googleapis.com/storage/v1/b/asset-inbox/o/assets%2Fabcde.png/copyTo/b/asset-storage/o/assets/abcde.png
```

Reverting back to 0.22.1 fixed the issue for us but wanted to raise the issue.

**Comment by lstrzebinczyk** [comment]
I'm glad I found this issue. I've spent some time wondering where did I break my code that this stopped working. Well then, I'm just leaving a note that it affected me too, and I would appreciate it fixed.
