### ISSUE TITLE
Rename this repository to "elixir-api-client"

### ISSUE THREAD

**Issue by bshaffer** [googleapis/elixir-google-api#69]
The name `elixir-google-api` seems like Google has a product called Elixir and this code exposes the API for it. Rather, this repository is the client library for google apis, so I think it would be a much better name `elixir-api-client`, with "google` being explicit via the Org name. 

Alternatively we could name it `elixir-google-api-client` or `elixir-google-client`

## What should the name of this repo be?

[![](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-google-api%20%28unchanged%29)](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-google-api%20%28unchanged%29/vote)
[![](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-api-client)](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-api-client/vote)
[![](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-google-api-client)](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-google-api-client/vote)
[![](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-google-client)](https://api.gh-polls.com/poll/01CBAQS8FJ1RWA37VDBEBAXKPH/elixir-google-client/vote)

**Comment by dazuma** [comment]
"elixir-api-client" also suggests there's an API called "elixir". Maybe "elixir-api-clients" (plural) or "elixir-google-api-clients" (to be most explicit)?

**Comment by dazuma** [comment]
@chingor13 @zeroasterisk @JustinBeckwith Any opinions on this?

**Comment by bshaffer** [comment]
I was thinking `google` was redundant since it's in the name of the org. For instance, if we hosted this on the `googleapis` org, we could just name this repo `elixir-client`.

**Comment by zeroasterisk** [comment]
It looks like other projects/repos are named `google-cloud-<lang>` and perhaps we should follow that pattern?
<img width="715" alt="google_cloud_platform" src="https://user-images.githubusercontent.com/23422/40396237-b8bb75e8-5de0-11e8-839d-6b45c422855c.png">

**Comment by bshaffer** [comment]
The problem is those API clients are fundamentally different. They are only for Google Cloud APIs, where as the APIs in this repository are for all Google APIs.

**Comment by fhinkel** [comment]
@bshaffer are we still thinking of renaming the repo or can we close this isuee?

**Comment by bshaffer** [comment]
It's up to @dazuma who now maintains this library. I'm fairly sure the name is fine and this can be closed.

**Comment by dazuma** [comment]
I think we eventually decided it doesn't matter that much. Closing.
