### ISSUE TITLE
GoogleApi.Firestore.V1.Api.Projects wrong spec

### ISSUE THREAD

**Issue by lok0613** [googleapis/elixir-google-api#7273]
https://github.com/googleapis/elixir-google-api/blob/141161dec057e357c1f758bae593d84223e4df87/clients/firestore/lib/google_api/firestore/v1/api/projects.ex#L1679

I think it should be
`{:ok, [GoogleApi.Firestore.V1.Model.RunQueryResponse.t()}]` instead.

**Comment by lok0613** [comment]
if I ran this function, it returns:
```
{:ok,
 [
   %GoogleApi.Firestore.V1.Model.RunQueryResponse{
     document: %GoogleApi.Firestore.V1.Model.Document{
 ...
```
Clearly, it is a list.

And I notice the official [REST API documentation](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases.documents/runQuery) shows that the result should be a JSON
```
{
  "transaction": string,
  "document": {
    object (Document)
  },
  "readTime": string,
  "skippedResults": integer
}
```
Is that something I'm missing?

**Comment by dazuma** [comment]
This may be a case of a streaming API. Normally a response shouldn't be a list, but there are a few exceptions, notably streaming APIs, that the generator can't detect from the discovery document, leading it to generate the wrong spec. Will take a closer look when I get the chance.

**Comment by lok0613** [comment]
Thanks for your time @dazuma. This issue causing my project loads of dialyzer warning, is there a way to disable/ignore the function spec from this package before you sort this issue out?

**Comment by dazuma** [comment]
Loosened the typespecs to allow for lists for all calls (since we're not able to determine from the discovery document which calls should be lists) in #7406. Will regenerate and rerelease all clients in the next couple days.
