### ISSUE TITLE
GoogleApi.Storage.V1.Api.Objects.storage_objects_copy fails for destination object with reserved chars

### ISSUE THREAD

**Issue by jheld** [googleapis/elixir-google-api#8476]
#### Environment details

  - Programming language: Elixir
  - OS: linux
  - Language runtime version: 1.10.4
  - Package version: 0.30.0

#### Steps to reproduce

  1. call the function with a destination object which has at least one reserved character in it (such as a `"/"`)

this is in the same vein as from issue https://github.com/googleapis/elixir-google-api/issues/6510

**Comment by pojiro** [comment]
I'd like to propose a change to fix this issue by this commit https://github.com/pojiro/elixir-google-api/commit/becaeaa42638925a16c2907e0cc902f8b4c112f8.

This fix improved https://github.com/googleapis/elixir-google-api/commit/fc4b2823b3f91c67ce102fd1d361842f0325225d and only affects `storage_objects_copy` and `storage_objects_rewrite`.
I checked the generating results,  https://github.com/pojiro/elixir-google-api/commit/2e34288f6978e0cace17c2c2f2e9551b2e49e524, this commit is just for checking generating results.

**Comment by pojiro** [comment]
@dazuma Could you check this issue and fix?

**Comment by montebrown** [comment]
@pojiro 🙏  btw this fix resolves the encoding problems I was seeing with storage_objects_copy.

**Comment by pojiro** [comment]
@chingor13 @dazuma I create a PR #8770 which needs `a maintainer to approve running workflows`. Could you see them?

**Comment by dazuma** [comment]
#8770 is merged. It should regenerate tonight. Google Cloud is currently in a release freeze for the holidays in North America, so the actual library release will happen next week.
