### ISSUE TITLE
connection error in Storage api

### ISSUE THREAD

**Issue by GanitGenius** [googleapis/elixir-google-api#87]
Hi, i'm getting this error when using service authentication.
I'm calling this in my code like this as specified in the repo.
I have exported the variable using: export GOOGLE_APPLICATION_CREDENTIALS=/path_to_jsonfile 
can someone please help, why this is happening.

```elixir   
 {:ok, token} = Goth.Token.for_scope("https://www.googleapis.com/auth/cloud-platform") #works fine
 conn = GoogleApi.Storage.V1.Connection.new(token.token)
```

[error] #PID<0.699.0> running ParserWeb.Endpoint (cowboy_protocol) terminated
Server: localhost:4000 (http)
Request: GET /api/v1/start/1111/2222
** (exit) an exception was raised:
    ** (KeyError) key :status not found in: %Tesla.Client{fun: nil, post: [], pre: [{Tesla.Middleware.Headers, :call, [%{"Authorization" => "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxx"}]}]}
        (phoenix) lib/phoenix/controller.ex:367: Phoenix.Controller.text/2
        (parser) lib/parser_web/controllers/page_controller.ex:1: ParserWeb.PageController.action/2
        (parser) lib/parser_web/controllers/page_controller.ex:1: ParserWeb.PageController.phoenix_controller_pipeline/2
        (parser) lib/parser_web/endpoint.ex:1: ParserWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (parser) lib/parser_web/endpoint.ex:1: ParserWeb.Endpoint.plug_builder_call/2
        (parser) lib/plug/debugger.ex:102: ParserWeb.Endpoint."call (overridable 3)"/2
        (parser) lib/parser_web/endpoint.ex:1: ParserWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/baldor/df/parser/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Comment by chingor13** [comment]
Can you add more information about which API method you're calling?

**Comment by nerdyworm** [comment]
Ran into this too.  Basically whats going on is that you are doing the following:

``` elixir
def index(conn, _) do
  {:ok, token} = Goth.Token.for_scope("https://www.googleapis.com/auth/cloud-platform") #works fine
  conn = GoogleApi.Storage.V1.Connection.new(token.token)
  # conn is no longer a Plug.Conn
  json(conn, %{})
end
```

Took me quite a while to realize what I was doing :)

**Comment by dazuma** [comment]
Agreed, it looks from the stack trace that nerdyworm's diagnosis is probably accurate. You'll need to use a different variable name. Sorry for that confusion. I'm going to close this, but please feel free to reopen if you're still having issues.
