### ISSUE TITLE
Is the new Google Identity's API available in this library?

### ISSUE THREAD

**Issue by astroTANSAN** [googleapis/elixir-google-api#8926]
I am looking at this page for verifying using your backend: https://developers.google.com/identity/gsi/web/guides/verify-google-id-token

I tried looking through the codebase and found identity toolkit, but I couldn't find a similar function for verifying ID token. Does this library support this?

**Comment by dazuma** [comment]
There isn't an API for "ID token verification". That's generally just done in a library, following the logic described in the link you posted. (For example, here is the implementation for Ruby: https://github.com/googleapis/google-auth-library-ruby/blob/main/lib/googleauth/id_tokens.rb). The logic isn't present in this repo; this repo only contains API clients, and it defers auth-related logic to a separate package such as goth.

There may be third-party libraries that provide some of the logic here. I don't have enough info to endorse a particular approach; however, a few possibilities that I found from a quick google search are:

* https://github.com/joken-elixir/joken
* https://github.com/amezcua/jwt-google-tokens
